### ISSUE TITLE
Blacklight::Document[] deprecation warning

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/orangelight#1041]
when executing
`$ bunx rspec spec/features/request_options_spec.rb:21`

```
DEPRECATION WARNING: Blacklight::Document#[]= is deprecated; use obj.to_h.[]= instead. (called from name_title_hierarchy at /Users/headleya/src/orangelight/app/helpers/application_helper.rb:472) (1 times); e.g.: 
    /Users/headleya/src/orangelight/app/helpers/application_helper.rb:472:in `name_title_hierarchy'
    /Users/headleya/.gem/ruby/2.2.3/bundler/gems/blacklight-1c54dcb6aa01/app/presenters/blacklight/rendering/helper_method.rb:15:in `render_helper'
    /Users/headleya/.gem/ruby/2.2.3/bundler/gems/blacklight-1c54dcb6aa01/app/presenters/blacklight/rendering/helper_method.rb:6:in `render'
    /Users/headleya/.gem/ruby/2.2.3/bundler/gems/blacklight-1c54dcb6aa01/app/presenters/blacklight/rendering/pipeline.rb:26:in `render'
    /Users/headleya/.gem/ruby/2.2.3/bundler/gems/blacklight-1c54dcb6aa01/app/presenters/blacklight/rendering/pipeline.rb:21:in `render'

```

**Comment by tampakis** [comment]
We have upgraded to Blacklight 7 and probably directly addressed this
