### ISSUE TITLE
Exclude theses from the electronic portfolio markup

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2486]
(For alma) We use the OnlineHoldingsMarkupBuilder to create and add the online links in the online section using the `electronic_portfolio_s` field. 
The same field is added in https://github.com/pulibrary/orangetheses/pull/59/files#diff-9415cee3ad92b38bfe0abb0a30dfbd15b181b9d03915e22ec0e1b0ea09fb2b44R416 to update holding locations for Theses using the orangetheses repository. 
The online section for theses is populated using the `electronic_access_1display` field and it only includes the ark identifier `"{\"http://arks.princeton.edu/ark:/88435/dsp01r207ts08x\":[\"DataSpace\",\"Full text\"]}"`
When the electronic_portfolio_s field has a thesis key we should exclude the creation of online links in the Online section.

**Comment by christinach** [comment]
The error that is triggered is: `ActionView::Template::Error (arguments passed to url_for can't be handled. Please require routes or provide your own implementation):
    1: <% online, physical = holding_request_block(document) %>
    2: <% unless holding_requests_adapter.restrictions.empty? %>
    3:   <div class="restrictions--panel alert alert-warning">
    4:     <span class="icon-warning" aria-hidden="true"></span> <%= PhysicalHoldingsMarkupBuilder.restrictions_markup(holding_requests_adapter.restrictions) %>
  
app/services/online_holdings_markup_builder.rb:113:in `block in electronic_portfolio_markup'
app/services/online_holdings_markup_builder.rb:108:in `each'
app/services/online_holdings_markup_builder.rb:108:in `electronic_portfolio_markup'
app/services/online_holdings_markup_builder.rb:152:in `online_holdings'
app/services/online_holdings_markup_builder.rb:161:in `online_holdings_block'
app/services/online_holdings_markup_builder.rb:131:in `build'
app/services/holding_requests_builder.rb:41:in `build'
app/helpers/application_helper.rb:102:in `holding_request_block'
app/views/catalog/_show_restrictions.html.erb:1:in `_app_views_catalog__show_restrictions_html_erb__253768953027409439_70072674902700'
app/views/catalog/show.html.erb:5:in `_app_views_catalog_show_html_erb__1154356256282703820_70072674420820'
lib/orangelight/middleware/invalid_parameter_handler.rb:12:in `call'`

**Comment by christinach** [comment]
closed by #2489
