### ISSUE TITLE
Flakey Test - unapi

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#3159]
Could possibly be related to https://github.com/pulibrary/orangelight/pull/3147/files ?

"Unapi support Show Page contains an unapi reference in an abbr tag"
`spec/features/unapi_spec.rb`

Link to example failed run - https://app.circleci.com/pipelines/github/pulibrary/orangelight/2813/workflows/c06da39c-92bb-461e-9f8a-571be579ec1a/jobs/6763/tests

Example failure:
```
Failures:

  1) Unapi support Show Page contains an unapi reference in an abbr tag
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: visit '/catalog/9932561773506421'
          
          Net::ReadTimeout:
            Net::ReadTimeout
          # ./spec/features/unapi_spec.rb:11:in `block (3 levels) in <top (required)>'

     1.2) Failure/Error: raise "Requests did not finish in 60 seconds: #{middleware.pending_requests}" if timer.expired?
          
          RuntimeError:
            Requests did not finish in 60 seconds: ["http://127.0.0.1:44811/catalog/9932561773506421"]
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/capybara-3.36.0/lib/capybara/server.rb:66:in `wait_for_pending_requests'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/capybara-3.36.0/lib/capybara/session.rb:133:in `reset!'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/capybara-3.36.0/lib/capybara.rb:325:in `block in reset_sessions!'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/capybara-3.36.0/lib/capybara.rb:325:in `reverse_each'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/capybara-3.36.0/lib/capybara.rb:325:in `reset_sessions!'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/capybara-3.36.0/lib/capybara/rspec.rb:20:in `block (2 levels) in <top (required)>'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:372:in `run'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:529:in `block in run_owned_hooks_for'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:528:in `each'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:528:in `run_owned_hooks_for'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:615:in `block in run_example_hooks_for'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:614:in `each'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:614:in `run_example_hooks_for'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:485:in `run'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:518:in `run_after_example'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:283:in `block in run'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:486:in `block in run'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:352:in `call'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-rails-5.1.1/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:390:in `execute_with'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:352:in `call'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:390:in `execute_with'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:352:in `call'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:486:in `run'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:259:in `run'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:642:in `map'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:642:in `run_examples'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:607:in `run'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `block in run'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `map'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `run'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `map'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:2068:in `with_suite_hooks'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/reporter.rb:74:in `report'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:115:in `run_specs'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:89:in `run'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:71:in `run'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:45:in `invoke'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/exe/rspec:4:in `<top (required)>'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/bin/rspec:25:in `load'
          # /home/circleci/orangelight/vendor/bundle/ruby/2.7.0/bin/rspec:25:in `<top (required)>'
          # /home/circleci/.rubygems/gems/bundler-2.2.27/lib/bundler/cli/exec.rb:58:in `load'
          # /home/circleci/.rubygems/gems/bundler-2.2.27/lib/bundler/cli/exec.rb:58:in `kernel_load'
          # /home/circleci/.rubygems/gems/bundler-2.2.27/lib/bundler/cli/exec.rb:23:in `run'
          # /home/circleci/.rubygems/gems/bundler-2.2.27/lib/bundler/cli.rb:477:in `exec'
          # /home/circleci/.rubygems/gems/bundler-2.2.27/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
          # /home/circleci/.rubygems/gems/bundler-2.2.27/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
          # /home/circleci/.rubygems/gems/bundler-2.2.27/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
          # /home/circleci/.rubygems/gems/bundler-2.2.27/lib/bundler/cli.rb:31:in `dispatch'
          # /home/circleci/.rubygems/gems/bundler-2.2.27/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
          # /home/circleci/.rubygems/gems/bundler-2.2.27/lib/bundler/cli.rb:25:in `start'
          # /home/circleci/.rubygems/gems/bundler-2.2.27/exe/bundle:49:in `block in <top (required)>'
          # /home/circleci/.rubygems/gems/bundler-2.2.27/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
          # /home/circleci/.rubygems/gems/bundler-2.2.27/exe/bundle:37:in `<top (required)>'
          # /home/circleci/.rubygems/bin/bundle:23:in `load'
          # /home/circleci/.rubygems/bin/bundle:23:in `<main>'
          # 
          #   Showing full backtrace because every line was filtered out.
          #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
          #   RSpec::Configuration#backtrace_inclusion_patterns for more information
```

**Comment by christinach** [comment]
See: https://app.circleci.com/insights/github/pulibrary/orangelight/workflows/build_accept/tests?branch=main

**Comment by christinach** [comment]
we haven't seen this happening recently
