### ISSUE TITLE
Review Deprecation Warnings in Current Blacklight 7 Release Branch

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3503]
1. Update to latest release of Blacklight 7. 
1. Run test suite and see if there are any deprecation warnings.
1. Create tickets for any un-ticketed deprecation warnings

**Comment by maxkadel** [comment]
One deprecation is coming from the Advanced Search gem, which we are working on upgrading in a separate ticket (#3412):
```
       DEPRECATION WARNING: default_search_field is deprecated and will be removed from a future release (Use Blacklight::Configuration#default_search_field). (called from add_advanced_parse_q_to_solr at /Users/kadelm/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/blacklight_advanced_search-7.0.0/lib/blacklight_advanced_search/advanced_search_builder.rb:54)
```

**Comment by maxkadel** [comment]
Remove the deprecation from the advanced search gem leaves only one deprecation (based on running the test suite)

```
  5) search requests for the catalog atom feed renders the page
     Failure/Error: xml.link    'rel' => 'alternate', 'type' => 'text/html', 'href' => polymorphic_url(url_for_document(document))

     ActionView::Template::Error:
       DEPRECATION WARNING: url_for_document is deprecated and will be removed from a future release (Use SearchState#url_for_document directly). (called from block in _app_views_catalog__document_default_atom_builder___2992284612096802835_1514880 at /Users/kadelm/projects/orangelight/app/views/catalog/_document_default.atom.builder:9)
     # ./app/views/catalog/_document_default.atom.builder:9:in `block in _app_views_catalog__document_default_atom_builder___2992284612096802835_1514880'
     # ./app/views/catalog/_document_default.atom.builder:3:in `_app_views_catalog__document_default_atom_builder___2992284612096802835_1514880'
     # ./app/controllers/catalog_controller.rb:689:in `index'
     # ./lib/orangelight/middleware/invalid_parameter_handler.rb:12:in `call'
     # ./spec/requests/catalog_spec.rb:38:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # RuntimeError:
     #   DEPRECATION WARNING: url_for_document is deprecated and will be removed from a future release (Use SearchState#url_for_document directly). (called from block in _app_views_catalog__document_default_atom_builder___2992284612096802835_1514880 at /Users/kadelm/projects/orangelight/app/views/catalog/_document_default.atom.builder:9)
     #   ./app/views/catalog/_document_default.atom.builder:9:in `block in _app_views_catalog__document_default_atom_builder___2992284612096802835_1514880'
```

It looks like we overrode these partials a good while ago, and the implementation in Blacklight has drifted a good bit since.
