### ISSUE TITLE
Investigate this error and fix it

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/orangelight#4471]
### What maintenance needs to be done?
When upgrading to Blacklight 8 we get the same failure in many tests. Investigate the error below and fix it in a way where it works in both Blacklight 7 and 8, if possible.

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
When upgrading to Blacklight 8 we get the same failure in many tests:

```
Failure/Error: <%= render BookmarkButtonComponent.new(document: @document) if current_or_guest_user %>

ActionView::Template::Error:
  undefined method `name' for nil:NilClass

          @id = id || @action.fetch(:id, "#{@action.name}Link")
                                                   ^^^^^
./app/views/catalog/_previous_next_doc.html.erb:52:in `new'
./app/views/catalog/_previous_next_doc.html.erb:52:in `_app_views_catalog__previous_next_doc_html_erb__1551705124890848459_78220'
./app/views/catalog/show.html.erb:1:in `_app_views_catalog_show_html_erb___4223457651520574876_78200'
./lib/orangelight/middleware/invalid_parameter_handler.rb:16:in `call'
./spec/requests/request_spec.rb:386:in `block (3 levels) in <top (required)>'
------------------
--- Caused by: ---
NoMethodError:
  undefined method `name' for nil:NilClass
  
          @id = id || @action.fetch(:id, "#{@action.name}Link")
                                                   ^^^^^
  ./app/views/catalog/_previous_next_doc.html.erb:52:in `new'
```

### Implementation notes, if any
There is [another ticket to update the _previous_next_doc to use a component](https://github.com/pulibrary/orangelight/issues/4187), see whether this resolves this issue.

**Comment by maxkadel** [comment]
Closed by #4484
